repository: hyperledger/firefly
logo: "images/hyperledger-firefly_color.svg"
title: Hyperledger FireFly Docs
ga_tracking: GTM-T6J7RQ
ga_tracking_anonymize_ip: true
baseurl: /firefly
aux_links:
  "GitHub":
    - "https://github.com/hyperledger/firefly"
  "Wiki":
    - "https://wiki.hyperledger.org/display/FIR"
  "Discord":
    - "https://discord.gg/hyperledger"
color_scheme: firefly
plugins:
  - jekyll-multiple-languages-plugin
languages: ["en"]
